name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --add-data "model;model/" \
        --collect-all "torch" --collect-all "torchaudio" --collect-all "torchvision" \
        --collect-all "tokenizers" --collect-all "charset-normalizer" --collect-all "MarkupSafe" \
        --collect-all "numpy" --collect-all "pillow" --collect-all "PyYAML" \
        --collect-all "regex" --collect-all "safetensors" --collect-all "transformers" \
        main.py

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: MyApp
        path: dist/main.exe